services:
  backend:
    build:
      context: ./Backend
    ports: 
      - "3000:3000"
    # environment: 
    #   - MONGO_URI=${MONGO_URI}
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    ports: 
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
